# GitHub Pages config

title: tsl-core-xml
description: TypeScript library for XML
author:
  name: Â© TypeScriptLibs and Contributors
  email: bug@typescriptlibs.eu

header_pages:
  - www/downloads.md
  - CHANGELOG.md
  - SECURITY.md
  - LICENSE.md
  - www/all-libraries.md

include:
  - CHANGELOG.md
  - LICENSE.md
  - README.md
  - SECURITY.md
  - www/all-libraries.md
  - www/downloads.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-titles-from-headings

remote_theme: jekyll/minima@2e9c7c0

minima:
  date_format: "%Y-%m-%d"
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/typescriptlibs/" }
    - { platform: mastodon, user_url: "https://mastodon.social/@typescriptlibs" }
    - { platform: rss,  user_url: "feed.xml" }

sass:
  quiet_deps: true

show_excerpts: false

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
